# Generated by Django 3.2.5 on 2021-11-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20211118_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_name',
        ),
    ]
