# Generated by Django 3.2.5 on 2021-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20211119_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='like_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
