# Generated by Django 3.2.5 on 2021-11-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20211119_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedportfolio',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedportfolio',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedportfolio',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedPortfolio',
        ),
    ]
